name: Build GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github io
        uses: actions/checkout@v4

      - name: Checkout latest snapshot adoc and image files
        uses: actions/checkout@v4
        with:
          repository: jbossws/jbossws-cxf
          path: './jbossws-cxf'
      - name: copy snapshot adoc files to github pages
        working-directory: './jbossws-cxf'
        run: |
          cp -R ./docbook/src/main/doc/adoc/content ../_documentation/latest
          cp -R ./docbook/src/main/doc/adoc/image ../_documentation/latest
      - name: remove jbossws-cxf
        run: |
          rm -rf jbossws-cxf
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build Jekyll site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: false
          prettier_ignore: '*'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site